#! /usr/bin/env bash

# uses entr to watch for changes: http://entrproject.org

# re-run any individual .bats file when it changes. -p to postpone the first execution, since the commands below will run all the .bats files.
shopt -s globstar
ls **/*.bats | entr -p bats /_ &

# re-run relevant tests when a source file changes.
echo deploy.sh | entr bats . &
ls  lib/*.bash | entr bats lib
