#! /usr/bin/env bash

# uses entr to watch for changes: http://entrproject.org

# re-run any individual .bats file when it changes. -p to postpone the first execution, since the 2nd entr command below will run all the .bats files.
ls *.bats | entr -p bats /_ &

# re-run all tests when the script under test changes.
echo deploy.sh | entr bats .
